<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/18/2018
Description:	Creates the DAL class for  contentitem table and respective stored procedures

*/



class Contentitem {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $Id;
	protected $ContentGroupId;
	protected $Name;
	protected $Description;
	protected $Content;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 5:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4] );
		}
	}


	public function __constructBase() {
		$this->Id = 0;
		$this->ContentGroupId = 0;
		$this->Name = "";
		$this->Description = "";
		$this->Content = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramContentGroupId,$paramName,$paramDescription,$paramContent) {
		$this->Id = $paramId;
		$this->ContentGroupId = $paramContentGroupId;
		$this->Name = $paramName;
		$this->Description = $paramDescription;
		$this->Content = $paramContent;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->Id;
	}
	public function setId($value){
		$this->Id = $value;
	}
	public function getContentGroupId(){
		return $this->ContentGroupId;
	}
	public function setContentGroupId($value){
		$this->ContentGroupId = $value;
	}
	public function getName(){
		return $this->Name;
	}
	public function setName($value){
		$this->Name = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getContent(){
		return $this->Content;
	}
	public function setContent($value){
		$this->Content = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['Id']);
		 $this->setContentGroupId($row['ContentGroupId']);
		 $this->setName($row['Name']);
		 $this->setDescription($row['Description']);
		 $this->setContent($row['Content']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_Add(?,?,?,?)');
		$arg1 = $this->getContentGroupId();
		$arg2 = $this->getName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getContent();
		$stmt->bind_param('isss',$arg1,$arg2,$arg3,$arg4);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_Update(?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getContentGroupId();
		$arg3 = $this->getName();
		$arg4 = $this->getDescription();
		$arg5 = $this->getContent();
		$stmt->bind_param('iisss',$arg1,$arg2,$arg3,$arg4,$arg5);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$contentitem = new Contentitem($row['Id'],$row['ContentGroupId'],$row['Name'],$row['Description'],$row['Content']);
				$arr[] = $contentitem;
			}
			return $arr;
		}
		else {
			return array();
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_Delete(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramContentGroupId,$paramName,$paramDescription,$paramContent) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_contentitem_Search(?,?,?,?,?)');
		$arg1 = Contentitem::setNullValue($paramId);
		$arg2 = Contentitem::setNullValue($paramContentGroupId);
		$arg3 = Contentitem::setNullValue($paramName);
		$arg4 = Contentitem::setNullValue($paramDescription);
		$arg5 = Contentitem::setNullValue($paramContent);
		$stmt->bind_param('iisss',$arg1,$arg2,$arg3,$arg4,$arg5);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$contentitem = new Contentitem($row['Id'],$row['ContentGroupId'],$row['Name'],$row['Description'],$row['Content']);
				$arr[] = $contentitem;
			}
			return $arr;
		}
		else {
			return array();
		}
	}
}
